version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: monthly
    time: "09:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: bower
    versions:
    - 1.8.8
  - dependency-name: browserify
    versions:
    - 3.46.1
